# Generated by Django 3.2 on 2021-07-12 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название опроса')),
                ('start_date', models.DateField(verbose_name='дата старта опроса')),
                ('finish_date', models.DateField(verbose_name='дата окончания опроса')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('text', 'Вопрос с текстовым ответом'), ('choises', 'Вопрос с выбором одного или нескольких вариантов')], default='text', max_length=16, verbose_name='тип вопроса')),
                ('number_of_answers', models.IntegerField(verbose_name='количество правильных ответов, для вопросов с вариантами')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Текст для текстовых ответов. Цифры, разделенные пробелами, для вопросов с вариантами', verbose_name='ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор ответа')),
            ],
            options={
                'verbose_name': 'ответ пользователя',
                'verbose_name_plural': 'ответы пользователя',
                'ordering': ('id',),
            },
        ),
    ]
