# Generated by Django 3.2 on 2021-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('text', 'Вопрос с текстовым ответом'), ('choices', 'Вопрос с выбором одного или нескольких вариантов')], default='text', max_length=16, verbose_name='тип вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_of_answers',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество правильных ответов, для вопросов с вариантами'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='текст вопроса'),
        ),
    ]
