# Generated by Django 3.2 on 2021-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210712_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.IntegerField(verbose_name='ID пользователя'),
        ),
    ]
